name: ESLint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Install NPM Dependencies
        uses: bahmutov/npm-install@v1

      - name: Cache ESLint
        uses: actions/cache@v4.3.0
        with:
          key: eslint-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json', 'eslint.config.*') }}-${{ github.run_id }}
          path: .eslintcache
          restore-keys: |
            eslint-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json', 'eslint.config.*') }}-
            eslint-cache-${{ runner.os }}-

      - name: Run ESLint
        run: npm run eslint:ci
